### ISSUE TITLE
Conditional decorators

### ISSUE THREAD

**Issue by arajar** [Velorth/SimpleBT#1]
Hi!

I was wondering how to use the conditional operators here. Can you create a quick example about it?
Thank you!

**Comment by Velorth** [comment]
Conditional decorator performs check every tick. If check fails node will fail, if not child node will run as usual.
You can use it this way: 
```
new Conditional
{
    Condition = context => your condition here,
    Child = new Sequence
    {
        Things to do...
    }
}
```
I think about replacement of Condition predicate with InVariable<bool> in future updates.

**Comment by arajar** [comment]
Thank you!
